name: CI/CD Pipeline for NestJS-MariaDB Project

# Trigger the workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t nestjs-app .

    # Step 5: Run tests (if any)
    - name: Run tests
      run: |
        npm run test

    # Optional: If you want to push to Docker Hub, uncomment and set up Docker credentials
    # Step 6: Push Docker image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag nestjs-app ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Deploy to your environment (e.g., AWS, DigitalOcean, etc.)
    - name: Deploy to your environment (Custom deployment)
      run: |
        # Add your deployment commands here (e.g., AWS CLI, kubectl commands, etc.)
